apps/zpids_web/lib/zpids_web/router.ex
defmodule Zpids.Web.Router do
  use Zpids.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.Pipeline, module: Zpids.Web.Guardian,
                                 error_handler: Zpids.Web.AuthErrorHandler
    plug Guardian.Plug.VerifySession, module: Zpids.Web.Guardian
    plug Guardian.Plug.LoadResource, module: Zpids.Web.Guardian, allow_blank: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Zpids.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    get "/login", SessionController, :login
    post "/login", SessionController, :create
    post "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Zpids.Web do
  #   pipe_through :api
  # end
end

apps/zpids_web/lib/zpids_web/controllers/page_controller.ex
defmodule Zpids.Web.PageController do
  use Zpids.Web, :controller

  def index(conn, _params) do
    case Guardian.Plug.current_resource(conn) do
      nil ->
        redirect conn, to: session_path(conn, :login)
      user ->
        {:ok, token, _claims} = Zpids.Web.Guardian.encode_and_sign(user)
        render conn, "index.html", token: token, user: user
    end
  end
end

apps/zpids_web/lib/zpids_web/controllers/session_controller.ex
defmodule Zpids.Web.SessionController do
  use Zpids.Web, :controller

  alias Zpids.Game.Account
  alias Zpids.Game.Account.User

  def login(conn, _params) do
    changeset = Account.change_user(%User{})
    render conn, "login.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    with %{"name" => name,
           "password" => password} <- user_params,
         {:ok, user} <- Account.check_password(name, password) do
      conn
      |> Zpids.Web.Guardian.Plug.sign_in(user)
      |> redirect(to: page_path(conn, :index))
    else
      x ->
        require Logger
        Logger.info(inspect x)
        redirect conn, to: session_path(conn, :login)
    end
  end

  def delete(conn, _) do
    conn
    |> Zpids.Web.Guardian.Plug.sign_out
    |> redirect(to: page_path(conn, :index))
  end
end

apps/zpids_web/lib/zpids_web/controllers/user_controller.ex
defmodule Zpids.Web.UserController do
  use Zpids.Web, :controller

  alias Zpids.Game.Account
  alias Zpids.Game.Account.User

  def new(conn, _params) do
    changeset = Account.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Account.create_user(user_params) do
      {:ok, user} ->
        conn
        |> Zpids.Web.Guardian.Plug.sign_in(user)
        |> redirect(to: page_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

apps/zpids_web/lib/zpids_web/views/error_view.ex
defmodule Zpids.Web.ErrorView do
  use Zpids.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

apps/zpids_web/lib/zpids_web/views/layout_view.ex
defmodule Zpids.Web.LayoutView do
  use Zpids.Web, :view
end

apps/zpids_web/lib/zpids_web/views/page_view.ex
defmodule Zpids.Web.PageView do
  use Zpids.Web, :view
end

apps/zpids_web/lib/zpids_web/views/session_view.ex
defmodule Zpids.Web.SessionView do
  use Zpids.Web, :view
end

apps/zpids_web/lib/zpids_web/views/user_view.ex
defmodule Zpids.Web.UserView do
  use Zpids.Web, :view
end

apps/zpids_web/lib/zpids_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Zpids</title>
  </head>

  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

apps/zpids_web/lib/zpids_web/templates/page/index.html.eex
<script>
window.token = "<%= @token %>"
window.userId = "<%= @user.id %>"
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/4.5.1/pixi.min.js"></script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

apps/zpids_web/lib/zpids_web/templates/session/login.html.eex
<h2>Sign in</h2>

<%= render Zpids.Web.UserView, "form.html", Map.put(assigns, :action, session_path(@conn, :create)) %>

<a href="<%= user_path(@conn, :new) %>">Create an account</a>

apps/zpids_web/lib/zpids_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

apps/zpids_web/lib/zpids_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>